env:
  commonjs: true
  es2021: true
  node: true
extends: [airbnb-base, prettier, plugin:prettier/recommended]
overrides:
  - files:
      - test/**/*.js
    rules:
      func-names: off
      prefer-arrow-callback: off
parserOptions:
  ecmaVersion: latest
rules:
  'no-unused-vars': ['error', { argsIgnorePattern: 'next' }]
  'prettier/prettier': 'error'
globals:
  expect: true
  browser: true
