name: Fake deploy from branch

env:
  NODE_ENV: development

on:
  push:
    branches-ignore:
      - main

jobs:
  echo_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Showing which branch is deployed during development
        run: 'echo Now deploying branch: $GITHUB_REF_NAME in ${{env.NODE_ENV}}'
