name: Fake deploy from branch

on:
  push:
    branches-ignore:
      - main

jobs:
  echo_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Showing which branch is deploying to test server
        run: 'echo Now deploying branch: $GITHUB_REF_NAME to the test server'
