name: Fake Production Deploy to main

env:
  NODE_ENV: production
  SECRET: ${{secrets.SECRET}}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_run:
    workflows: ['build-and-push-image'] # runs after code_quality workflow
    types:
      - completed

jobs:
  echo_branch:
    runs-on: ubuntu-latest

    steps:
      - name: first message
        run: 'echo Now deploying to ${{env.NODE_ENV}}'
      - name: docker image
        run: 'echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-$GITBHUB_SHA::7'
      - name: Show secret env
        run: 'echo ${{env.SECRET}}'
