name: Fake Production Deploy to main

env:
  NODE_ENV: production
  SECRET: ${{ secrets.SECRET }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_run:
    workflows:
      - Create and publish a Docker image
    types:
      - completed

  push:
    branches:
      - main

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Showing deployment message
        run: 'echo Now deploying to ${{env.NODE_ENV}}'

      - name: Add SHORT_SHA env property
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: docker image
        run: 'echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${GITHUB_SHA}'
      - name: Show secret env
        run: 'echo ${{env.SECRET}}'
