name: Fake Production Deploy to main

env:
  NODE_ENV: production
  SECRET: ${{secrets.SECRET}}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SHA: ${{ github.sha }}

on:
  workflow_run:
    workflows: ['Create and publish a Docker image'] # runs after code_quality workflow
    types:
      - completed

  push:
    branches-ignore:
      - main

jobs:
  echo_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Showing deployment message
        run: 'echo Now deploying to ${{env.NODE_ENV}}'

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: docker image
        run: 'echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${SHORT_SHA}'
      - name: Show secret env
        run: 'echo ${{env.SECRET}}'
