name: Fake Production Deploy to main

env:
  NODE_ENV: production
  SECRET: ${{ secrets.SECRET }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_run:
    workflows:
      - Test
      - Create and publish a Docker image
    types:
      - completed

  push:
    branches-ignore:
      - main

jobs:
  check-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Check workflow status
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo '{completed}={success}' >> $GITHUB_OUTPUT
          else
            echo '{completed}={failure}' >> $GITHUB_OUTPUT
          fi

  dependent-job-success:
    needs: check-workflows
    if: ${{ needs.check.outputs.completed == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Showing deployment message
        run: 'echo Now deploying to ${{env.NODE_ENV}}'

      - name: Add SHORT_SHA env property
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: docker image
        run: 'echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${GITHUB_SHA}'
      - name: Show secret env
        run: 'echo ${{env.SECRET}}'

  dependent-job-failure:
    needs: check-workflows
    if: ${{ needs.check.outputs.completed == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Print failure message
        run: echo "One or both workflows failed."
