name: Test

on:
  push:
    branches:
      - main

env:
  WELCOME_PHRASE: Welcome

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: npm install
      - name: npm lint
        run: npm run lint
      - name: Run project unit tests
        run: npm run test
