name: Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

env:
  WELCOME_PHRASE: Welcome

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Greating
        run: echo $WELCOME_PHRASE
      - name: Installing dependencies
        run: npm install
      - name: Running lining check
        run: npm run lint
      - name: Run project unit tests
        run: npm run test
      - name: Checking coverage on project unit tests
        run: npm run nyc
      - name: Run project integration tests
        run: npm run test:integration
      - name: Run project selenium tests
        run: npm run wdio
