name: Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

env:
  WELCOME_PHRASE: Welcome

jobs:
  code_quality:
    runs-on:
      ubuntu-latest

      # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      nginx:
        # Docker Hub image
        image: nginx:alpine
        #
        ports:
          # Opens tcp port 8080 on the host and service container
          - 8080:80

    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Greating
        run: echo $WELCOME_PHRASE

      - name: Installing dependencies
        run: npm install

      - name: Running linting check
        run: npm run lint

      - name: Run project unit tests
        run: npm run test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Mocha Tests
          path: test-result/unit-test-report.json
          reporter: mocha-json
          fail-on-error: true

      - name: Checking coverage on project unit tests
        run: npm run nyc

      - name: Smoke test with curl
        run: curl http://localhost:8080

      - name: Run project integration tests
        run: npm run test:integration
